In [2]:
!pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 6.0 MB/s eta 0:00:02
   ----- ---------------------------------- 1.6/12.6 MB 4.6 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.6 MB 4.2 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.6 MB 4.3 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.6 MB 4.2 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.6 MB 4.2 MB/s eta 0:00:02
   -------------------- ------------------- 6.3/12.6 MB 4.3 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.6 MB 4.3 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.6 MB 4.2 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.6 MB 4.2 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.6 MB 4.2 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.6 MB 4.2 MB/s eta 0:00:01
   --

In [3]:
import numpy as np 
a = np.array([1,2,3])
b = np.array((1,2,3))
print(a)
print(b)

[1 2 3]
[1 2 3]


In [4]:
b[1]=4

In [5]:
b

array([1, 4, 3])

In [7]:
c= np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [8]:
c[0]


array([1, 2, 3])

In [9]:
c[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a[1:3]

array([2, 3])

In [12]:
a= np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
a=np.arange(10,25,5)
print(a)

[10 15 20]


In [14]:
a=np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [15]:
c= np.full((3,4),5)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
d= np.random.random((3,4))
print(d)

[[0.1338468  0.9186682  0.11899144 0.52624798]
 [0.76680892 0.35966834 0.42790354 0.71934597]
 [0.03181066 0.57729023 0.71955814 0.41275151]]


In [17]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)



[[1 2 3]
 [4 5 6]]
(2, 3)


In [24]:
#can change the no row and colume
a.shape=(3,2)
print(a.shape[0])
print(a.shape[1])
print(a.ndim)
print(a)

ValueError: cannot reshape array of size 24 into shape (3,2)

In [19]:
#give element between 0 to till end no
a=np.arange(24)
a.size
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [20]:
a.size

24

In [25]:
a.dtype

dtype('int64')

In [27]:
b=np.linspace(5,7,11)
print(b)
print(b.dtype)

[5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7. ]
float64


In [28]:
a=np.array([5,10])
np.sum(a)

np.int64(15)

In [32]:
b=[2,3]
print(np.sum([a,b]))
print(np.subtract(a,b))

20
[3 7]


In [34]:
np.sum([a,b], axis=1)# add row wise

array([15,  5])

In [35]:
print(np.divide(a,b))

[2.5        3.33333333]


In [36]:
print(np.multiply(a,b))

[10 30]


In [37]:
print(np.cos(a))

[ 0.28366219 -0.83907153]


In [38]:
a=[1,2,3]
b=[4,5,6]
print(np.equal(a,b))
print(np.array_equal(a,b))

[False False False]
False


In [45]:
a=np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.median(a))
print(np.corrcoef(a))


21
1
6
3.5
1.707825127659933
3.5
[[1. 1.]
 [1. 1.]]


In [46]:
#broadcasting

In [50]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([3,4,5])
print(a)
print(b)
print(np.sum([a,b]))

[[1 2 3]
 [4 5 6]]
[3 4 5]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [51]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([3,4,5])
print(a)
print(b)
print(np.subtract(a,b))

[[1 2 3]
 [4 5 6]]
[3 4 5]
[[-2 -2 -2]
 [ 1  1  1]]


In [52]:
#indexing and slicing

In [57]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[0])
print(a[:1])
print(a[:1,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[[1 2 3]]
[[2 3]]


In [59]:
print(a[:2,2:])

[[3]
 [6]]


In [60]:
#manipulation

In [73]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,4,5],[5,6,7]])
print(np.concatenate([a,b],axis=0))
print(np.concatenate([a,b],axis=1))


[[1 2 3]
 [4 5 6]
 [3 4 5]
 [5 6 7]]
[[1 2 3 3 4 5]
 [4 5 6 5 6 7]]


In [69]:
print(np.stack((a,b),axis=0))

[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [5 6 7]]]


In [70]:
print(np.hstack((a,b)))# it is same as vertical concatenate

[[1 2 3 3 4 5]
 [4 5 6 5 6 7]]


In [71]:
print(np.vstack((a,b)))#same as hori concatenate

[[1 2 3]
 [4 5 6]
 [3 4 5]
 [5 6 7]]


In [72]:
np.arange(1,10,3)

array([1, 4, 7])

In [74]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [75]:
np.random.random(10)

array([0.07713551, 0.65351727, 0.49888108, 0.01818519, 0.66823388,
       0.86506186, 0.90376008, 0.1499317 , 0.87852345, 0.03489348])

In [76]:
x=np.arange(1,10)

In [77]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.random.shuffle(x)

In [82]:
np.random.randint(1,5,10)

array([3, 2, 2, 2, 2, 4, 4, 2, 2, 1], dtype=int32)

In [84]:
x= np.random.randint(1,5,10)

In [85]:
np.unique(x)

array([1, 2, 3, 4], dtype=int32)

In [86]:
x

array([2, 4, 4, 1, 4, 3, 1, 2, 2, 1], dtype=int32)

In [87]:
x=np.random.randint(1,10,10)

In [88]:
x

array([8, 8, 7, 8, 7, 7, 4, 9, 1, 8], dtype=int32)

In [89]:
np.where(x==2)

(array([], dtype=int64),)

In [91]:
x=np.zeros((10,10))

In [92]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [93]:
np.ravel(x)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [95]:

np.repeat(np.arange(3),5)


array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [96]:
np.tile(np.arange(3),5)

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])

In [97]:
np.diff([9,1,4,5,8])

array([-8,  3,  1,  3])

In [99]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
x=np.arange(1,10)

In [101]:
np.compress(x%2==0 ,x)

array([2, 4, 6, 8])

In [102]:
np.compress([True,False,False,True],x)

array([1, 4])

In [103]:
np.random.randint(1,10,10)

array([3, 1, 8, 4, 4, 9, 4, 5, 2, 5], dtype=int32)

In [104]:
x=np.random.randint(1,10,10)

In [106]:
np.clip(x,5,6)

array([5, 5, 5, 5, 5, 6, 5, 6, 6, 5], dtype=int32)

In [107]:
x


array([2, 3, 3, 5, 5, 6, 1, 9, 6, 4], dtype=int32)

In [108]:
#splitting array

In [109]:
a=np.arange(10)

In [110]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
np.split(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [114]:
np.array_split(a,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]

In [115]:
np.hsplit(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [117]:
c=np.arange(6).reshape(2,3)

In [118]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [122]:
np.vsplit(c,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

In [124]:
#asarray,frombuffer,frommiter

In [125]:
a=np.array([10,20,30,40,50])

In [126]:
print(a)

[10 20 30 40 50]


In [127]:
res=np.asarray(a,dtype="float",order="c")
print(res)

[10. 20. 30. 40. 50.]


In [128]:
b=np.array([[10,20,30],[40,50,60]])
print(b)

[[10 20 30]
 [40 50 60]]


In [130]:
res1=np.asarray(b,dtype="int",order="F")
print(res1)

[[10 20 30]
 [40 50 60]]


In [133]:
for i in np.nditer(res1):
     print(i)

10
40
20
50
30
60


In [136]:
res2=np.asarray(b,dtype="int",order="C")
print(res2)


[[10 20 30]
 [40 50 60]]


In [137]:
for i in np.nditer(res2):
     print(i)

10
20
30
40
50
60


In [138]:
#datatype


In [139]:
a=np.array([1,2,3,4,5])
print(a)
print(a.dtype)

[1 2 3 4 5]
int64


In [141]:
a=np.array(['10','20','30','40','50'])
print(a)
print(a.dtype)

['10' '20' '30' '40' '50']
<U2


In [142]:
a=np.array(['10','20','30','40','50'],dtype="i")
print(a)
print(a.dtype)

[10 20 30 40 50]
int32


In [143]:
b=a.astype("U")
print(b)
print(b.dtype)


['10' '20' '30' '40' '50']
<U11


In [154]:
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [147]:
c=a.copy()
print("COPY=",c)

COPY= [10 20 30 40 50]


In [148]:
c[1]=100

In [149]:
c

array([ 10, 100,  30,  40,  50])

In [150]:
a

array([10, 20, 30, 40, 50])

In [151]:
v=a.view()
print("VIEW",v)

VIEW [10 20 30 40 50]


In [159]:
v[1]=300

In [160]:
v

array([ 10, 300, 300,  40,  50])

In [161]:
a

array([10, 20, 30, 40, 50])

In [ ]:
#sorting

In [162]:
a=np.array([50,40,10,20,30])
print(a)

[50 40 10 20 30]


In [163]:
np.sort(a)

array([10, 20, 30, 40, 50])

In [165]:
b=np.array([[50,40,30],[20,10,90]])
print(b)

[[50 40 30]
 [20 10 90]]


In [166]:
np.sort(b,axis=0)

array([[20, 10, 30],
       [50, 40, 90]])

In [167]:
np.sort(b)

array([[30, 40, 50],
       [10, 20, 90]])